apiVersion: v1
kind: Service
metadata:
  name: movie-me-service
  labels:
    run: movie-me-service
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: movie-me