apiVersion: v1
kind: Service
metadata:
  name: movie-me
  labels:
    app: movie-me
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.deployment.containerPortName }}
      nodePort: 30007 #https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport not necessary but clarify for better understanding
  selector:
    app: movie-me